# Generated by Django 5.1.1 on 2024-10-02 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'verbose_name': 'Порода', 'verbose_name_plural': 'Породы'},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'verbose_name': 'Котик', 'verbose_name_plural': 'Котики'},
        ),
    ]
