# Generated by Django 5.1.1 on 2024-10-02 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_show', '0002_alter_breed_options_alter_cat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(default=0, upload_to='photo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats_show.breed'),
        ),
    ]
