# Generated by Django 5.1.1 on 2024-10-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_show', '0003_cat_photo_alter_cat_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
