# Generated by Django 5.1.1 on 2024-10-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_show', '0004_alter_cat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
