# Generated by Django 5.1.1 on 2024-10-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_show', '0006_alter_cat_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1),
        ),
    ]
