# Generated by Django 5.1.1 on 2024-10-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats_show', '0008_alter_cat_color_alter_cat_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='user',
            new_name='owner',
        ),
    ]
