# Generated by Django 5.1.1 on 2024-10-04 13:52

import cats_show.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_show', '0009_rename_user_cat_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='rating',
            field=models.IntegerField(default=0, validators=[cats_show.models.validate_range]),
            preserve_default=False,
        ),
    ]
