# Generated by Django 5.1.1 on 2024-10-04 14:14

import cats_show.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_show', '0010_cat_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='rating',
            field=models.FloatField(validators=[cats_show.models.validate_range]),
        ),
    ]
